[package]
name = "sol2cw"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = { workspace = true }
sol2cw_lexer = { workspace = true }
